apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: employees
spec:
  imagePullSecrets:
    - name: ecrcred
  containers:
    - name: webapp
      image: 998727131331.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp:latest
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: "mysql"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "passwors"
        - name: DBPORT
          value: "3306"
